### ISSUE TITLE
No connection.

### ISSUE THREAD

**Issue by DolleDries** [vitalets/docker-tizen-webos-sdk#1]
Cannot get the API from my TV (curl IPno:8001/api/v2). Hence  the 'sdb' doen't  work either. I've  a  pre 2011 TV.... However I can see my TV connecting to my server (sync to/with server)......

**Comment by vitalets** [comment]
Hi! Could you provide the full model of your tv? 
Samsung TVs with legacy OS (Orsay) don't have sdb/http API.

**Comment by DolleDries** [comment]
> Hi! Could you provide the full model of your tv?
> Samsung TVs with legacy OS (Orsay) don't have sdb/http API.
>

Hoi! I believe it id UE46ES6560 (european issue).

If this proves to be incomplete let me know...

> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/vitalets/docker-tizen-webos-sdk/issues/1#issuecomment-685698773


--
               Andre van der Vlies <andre@vandervlies.xs4all.nl>
               Certifiable Linux/UNIX engineer (CLUE)
               Homepage: http://vandervlies.xs4all.nl/~andre
--
    'Reality is that which, when you stop believing in it, doesn't go away.'
                    -  Philip K. Dick
    # vim: ts=4 sw=4 ff=unix sm ai ic:

    ^[^#]
--

**Comment by vitalets** [comment]
it's 2012 year model. It does not support `sdb` and `tizen` api.
