### ISSUE TITLE
The system cannot find the specified by LinuxEngine

### ISSUE THREAD

**Issue by vladyn** [vitalets/docker-tizen-webos-sdk#13]
On Windows 11 and elevated PowerShell 6.5 I've got the following error: 
```
docker run -it --rm -v tvdata:/home/developer docker-tizen-webos-sdk bash
docker: error during connect: this error may indicate that the docker daemon is not running: Head "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
```
I have the same when I run the command without -it. How can I run this container and access the Tyzen under this OS?

**Comment by vitalets** [comment]
Do other docker commands work, e.g. `docker version` or `docker run hello-world`?

**Comment by vladyn** [comment]
I have it installed on Hyper-V, and the Docker starts. I hope it will work, too - right? 
Other than that, I think my PC lacks resources.

**Comment by vitalets** [comment]
It should work, yes.
Did you try with raw tizen studio - are there enough resources for it to start?

**Comment by vladyn** [comment]
I didn't. But yesterday, I learned about its existence :) And especially that it is for windows. I thank you, @vitalets, for your quick answer and supportive presence! I have to close this.
