### ISSUE TITLE
This probably doesn't work for Docker Desktop for Mac due to lack of host network support right?

### ISSUE THREAD

**Issue by jfrux** [vitalets/docker-tizen-webos-sdk#3]

**Comment by vitalets** [comment]
I works on my Mac. 
Could you explain, what you mean under "lack of host network support"?

**Comment by jfrux** [comment]
`curl http://10.168.3.156:8001/api/v2` works from host but from within the guest it says Failed to connect on MacOS

**Comment by vitalets** [comment]
Could you check what is the [network mode](https://docs.docker.com/network/) of running container?

**Comment by jfrux** [comment]
According to the docs, bridge is default.  I also tried host.  But macvlan is not an option on MacOS of course.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jfrux** [comment]
Okay so... I figured it out... for some reason Docker for Mac had the `"buildkit":  true` feature enabled in the configuration of Docker for Mac.

It changes how networks work by default so I was not getting connected... What a waste of time... sorry to have bothered you!

**Comment by vitalets** [comment]
Never mind!
