### ISSUE TITLE
curious what your workflow looks like for this...

### ISSUE THREAD

**Issue by jfrux** [vitalets/docker-tizen-webos-sdk#4]
Let's say you had an existing project you build currently for WebOS / Tizen... what's a rough overview of how you would lay that out or implement this new environment to produce builds?

I'm just trying to visualize how this ties into your workflow on a new project, versus existing projects, etc.

Is there something that connects all of it together at all or do you just build your apps separately and just use this to package them?

I have scripts that inject the JS libs for different TV platforms depending on the platform my app is to be released on.  I'm wanting to include a more consistent tizen/webos env to run the builds through so I'm hoping this is the answer.

**Comment by jfrux** [comment]
and thank you so much for your time and efforts working on this over the years!

**Comment by jfrux** [comment]
and if you have a donation page or venmo I can throw you some bones if you're interested.

**Comment by vitalets** [comment]
@jfrux Sorry for the silence, I was out of this repo for a while.
The workflow mainly is following: any member of your team can build and deploy TV app from the local machine without installing Tizen Studio and webOS CLI. This is the main benefit.

> and thank you so much for your time and efforts working on this over the years!

You are welcome!

> and if you have a donation page or venmo I can throw you some bones if you're interested.

Frankly, this repo does not take much time. I'm happy with the feedback that it is helpful for you and other developers ☺️
