### ISSUE TITLE
I'm unable to install any Tizen packages

### ISSUE THREAD

**Issue by geethu-rajasekharan** [vitalets/docker-tizen-webos-sdk#6]
Hi,

I am unable to install a certificate for packaging my app. When I troubleshot, it turns out that the certificate manager is not installed. So then I tried listing the packagees installed/ the ones available. the package-manager-cli is also not recognizable. Am I missing something?

**Comment by vitalets** [comment]
Hi @geethu-rajasekharan Sorry for the silence.
If it's still relevant, could you try with the latest [3.0 tag](https://hub.docker.com/repository/docker/vitalets/tizen-webos-sdk/tags?page=1&ordering=last_updated) that contains Tizen Studio 5.5?

**Comment by Ricrdsson1** [comment]
Yes, this really doesn't work. It's because you can't run package-manager-cli.bin as root. I can create a patch when the main user is Developer, but I have no idea if it might break something else. I haven't found any problems yet. @vitalets  Why are we acting as root user?

**Comment by Ricrdsson1** [comment]
Ok, it seems that running docker with `run docker --user developer` solves the problem

**Comment by vitalets** [comment]
Guys, could you provide more details and I will add it to readme? `developer` user should be created on the host machine? As now in readme we explicitly ask to run as a root.

**Comment by Ricrdsson1** [comment]
Just don't use the command
`docker run -it --rm -v tvdata:/home/developer vitalets/tizen-webos-sdk bash`
But fix it to `docker run --user developer -it --rm -v tvdata:/home/developer vitalets/tizen-webos-sdk bash`

This will switch the root user to the developer user. But it may cause other problems elsewhere with permissions.

**Comment by vitalets** [comment]
Updated readme, thank you!
