### ISSUE TITLE
Support mutli-arch container build

### ISSUE THREAD

**Issue by Georift** [vitalets/docker-tizen-webos-sdk#7]
Hello, I'm using this awesome project over at [Georift/install-jellyfin-tizen](https://github.com/Georift/install-jellyfin-tizen) to simplify the installation process of some apps on a Tizen system.

We ran into [some issues](https://github.com/Georift/install-jellyfin-tizen/issues/10) running it on a Raspberry pi so now I'm looking into what it will take to support multi-arch builds in my project and also over here.

Take everything I say with a grain of salt, I've not done multi-arch builds before.

From my reading [Tizen seems to support raspberry pi natively](https://docs.tizen.org/iot/get-started/rpi3-5.0/) so I think that means `arm64` is on the table.

Building `linux/arm/v7` without any changes in this repo has some issues, as we're expecting it to be 64 bit, and `arm/v7` is 32 bit.

So for now I'm focusing on `linux/arm64` which I believe checks of:
- Pi 3 B+
- Pi 4
- **NOT** Pi Zero W (as that's 32-bit)

Let me know if you have any thoughts, and if you'd be interested in a PR to this project with the changes.

**Comment by vitalets** [comment]
Hi @Georift !
I also don't have much experience with multi-platform builds. From docker docs I see [it is possible with `docker buildx` ](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)command, with just enumerating target platforms. But there maybe pitfalls.
I'm ready to accept PR for sure.

**Comment by bdovaz** [comment]
Are we sure it is possible? There must be an installer for ARM64 and looking at the installers listed, I don't think there isn't.

Example of latest version (5.1): http://download.tizen.org/sdk/Installer/tizen-studio_5.1/

The is only an Ubuntu version (amd, not arm).

**Comment by Georift** [comment]
Ah yeah perhaps it's not. I think the page I linked was using raspberry pi as a deploy target of the Tizen IDE. Not something that can run it. I'm going to close this for now, I don't think there is anything we can do unless it supports arm :facepalm:
