### ISSUE TITLE
Which WebOS version can we test / debug with this?

### ISSUE THREAD

**Issue by tejas-hosamani** [vitalets/docker-tizen-webos-sdk#8]
Possible to change WebOS versions to debug specifically for those devices?

**Comment by vitalets** [comment]
Yes, you can build docker container with required webOS version.
Have a look on this https://github.com/vitalets/docker-tizen-webos-sdk#update-webos-sdk
I've noticed that link to WebOS cli download is outdated, the correct link is:
https://webostv.developer.lge.com/develop/tools/cli-installation

**Comment by vitalets** [comment]
Updated to the latest webos cli version: **1.12.4-j27**
[Released as 3.0](https://hub.docker.com/repository/docker/vitalets/tizen-webos-sdk/tags?page=1&ordering=last_updated)
